TEAM_X = 1133
TEAM_POS = {1: (TEAM_X, 62),
            2: (TEAM_X, 203),
            3: (TEAM_X, 340),
            4: (TEAM_X, 477),
            5: (TEAM_X, 611),
            6: (TEAM_X, 741)}
NAME_X = 1275
NAME_POS = {1: (NAME_X, 90),
            2: (NAME_X, 230),
            3: (NAME_X, 370),
            4: (NAME_X, 500),
            5: (NAME_X, 640),
            6: (NAME_X, 770)}
BADGES_POS = (1695, 475)
DEATHS_POS = (1695, 295)
EVOLVE = {'bulbasaur': 'ivysaur',
          'ivysaur': 'venusaur',
          'charmander': 'charmeleon',
          'charmeleon': 'charizard',
          'squirtle': 'wartortle',
          'wartortle': 'blastoise',
          'caterpie': 'metapod',
          'metapod': 'butterfree',
          'weedle': 'kakuna',
          'kakuna': 'beedrill',
          'pidgey': 'pidgeotto',
          'pidgeotto': 'pidgeot',
          'rattata': 'raticate',
          'spearow': 'fearow',
          'ekans': 'arbok',
          'pikachu': 'raichu',
          'sandshrew': 'sandslash',
          'nidoran-f': 'nidorina',
          'nidorina': 'nidoqueen',
          'nidoran-m': 'nidorino',
          'nidorino': 'nidoking',
          'clefairy': 'clefable',
          'vulpix': 'ninetales',
          'jigglypuff': 'wigglytuff',
          'zubat': 'golbat',
          'oddish': 'gloom',
          'gloom': {'level': 'vileplume', 'sun': 'bellossom'},
          'paras': 'parasect',
          'venonat': 'venomoth',
          'diglett': 'dugtrio',
          'meowth': 'persian',
          'psyduck': 'golduck',
          'mankey': 'primeape',
          'growlithe': 'arcanine',
          'poliwag': 'poliwhirl',
          'poliwhirl': {'level': 'poliwrath', 'trade': 'politoed'},
          'abra': 'kadabra',
          'kadabra': 'alakazam',
          'machop': 'machoke',
          'machoke': 'machamp',
          'bellsprout': 'weepinbell',
          'weepinbell': 'victreebel',
          'tentacool': 'tentacruel',
          'geodude': 'graveler',
          'graveler': 'golem',
          'ponyta': 'rapidash',
          'slowpoke': {'level': 'slowbro', 'trade': 'slowking'},
          'magnemite': 'magneton',
          'doduo': 'dodrio',
          'seel': 'dewgong',
          'grimer': 'muk',
          'shellder': 'cloyster',
          'gastly': 'haunter',
          'haunter': 'gengar',
          'drowzee': 'hypno',
          'krabby': 'kingler',
          'voltorb': 'electrode',
          'exeggcute': 'exeggutor',
          'cubone': 'marowak',
          'koffing': 'weezing',
          'rhyhorn': 'rhydon',
          'horsea': 'sedra',
          'goldeen': 'seaking',
          'staryu': 'starmie',
          'magikarp': 'gyarados',
          'eevee': {'lightning': 'jolteon', 'fire': 'flareon', 'water': 'vaporeon', 'day': 'espeon',
                    'night': 'umbreon'},
          'omanyte': 'omastar',
          'kabuto': 'kabutops',
          'dratini': 'dragonair',
          'dragonair': 'dragonite',
          'chickorita': 'bayleef',
          'bayleef': 'meganium',
          'cyndaquil': 'quilava',
          'quilava': 'typhlosion',
          'totodile': 'croconaw',
          'croconaw': 'feraligatr',
          'sentret': 'furret',
          'hoothoot': 'noctowl',
          'ledyba': 'ledian',
          'spinarak': 'ariados',
          'golbat': 'crobat',
          'chinchou': 'lanturn',
          'pichu': 'pikachu',
          'cleffa': 'clefairy',
          'igglybuff': 'jigglypuff',
          'togepi': 'togetic',
          'natu': 'xatu',
          'mareep': 'flaaffy',
          'flaaffy': 'ampharos',
          'marill': 'azumarill',
          'hoppip': 'skiploom',
          'skiploom': 'jumpluff',
          'sunkern': 'sunflora',
          'wooper': 'quagsire',
          'pineco': 'forretress',
          'onix': 'steelix',
          'snubbull': 'granbull',
          'scyther': 'scizor',
          'teddiursa': 'urasing',
          'slugma': 'magcargo',
          'swinub': 'piloswine',
          'remoraid': 'octillery',
          'houndour': 'houndoom',
          'sedra': 'kingdra',
          'phanpy': 'donphan',
          'porygon': 'porygon2',
          'tyrogue': {'lee': 'hitmonlee', 'chan': 'hitmonchan', 'top': 'hitmontop'},
          'smoochum': 'jynx',
          'elekid': 'electabuzz',
          'magby': 'magmar',
          'larvitar': 'pupitar',
          'pupitar': 'tyranitar'}
